spring:
  application:
    name: cleanPR
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
  datasource:
    url:  ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update   # creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

client:
  url: ${CLIENT_URL}

jwt:
  secret.key: ${JWT_SECRET}


server:
  port: ${PORT:8081}

# used to generate JWT tokens for authentication to github
github:
  appId: 1953390
  key: ${CLEAN_PR_PEM}

#logging:
#  level:
#    root: DEBUG



