spring:
  application:
    name: cleanPR
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${openai.api-key}
      chat:
        options:
          model: gpt-4o
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${gitHubClientId}
            client-secret: ${gitHubClientSecret}
            scope:
              - read:user
              - user:email
  datasource:
    url:  ${postgres.url}
    username: ${postgres.name}
    password: ${postgres.password}
  jpa:
    hibernate:
      ddl-auto: update   # creates/updates tables automatically
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

client:
  url: "http://localhost:3000"

jwt:
  secret.key: ${jwtSecret}


server:
  port: ${PORT:8081}

# used to generate JWT tokens for authentication to github
github:
  appId: 1953390
  key: C:\Users\fahda\Downloads\clean-pr.2025-12-25.private-key.pem

#logging:
#  level:
#    root: DEBUG



